### ISSUE TITLE
Uncaugth exception when trying to read some messed up file

### ISSUE THREAD

**Issue by pleasedontbelong** [ewjoachim/raincoat#24]
I got the following error:

```
Traceback (most recent call last):
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/bin/raincoat", line 8, in <module>
    sys.exit(main())
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/raincoat/__init__.py", line 67, in main
    for line in errors:
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/raincoat/__init__.py", line 65, in <genexpr>
    color=color))
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/raincoat/glue.py", line 34, in raincoat
    key=class_key_name)
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/raincoat/grep.py", line 79, in find_in_dir
    for match in find_in_file(python_file):
  File "/home/pablo/workspace/peopleapi-drf-toolkit/.tox/linters/lib/python3.6/site-packages/raincoat/grep.py", line 43, in find_in_file
    return find_in_string(handler.read(), filename)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 81: invalid start byte
```
because raincoat was tying to read [this file](https://github.com/ipython/ipython/blob/master/IPython/core/tests/nonascii.py)

possible solution:

### grep.py
```
def find_in_file(filename):
    with open(filename) as handler:
        try:
            return find_in_string(handler.read(), filename)
        except UnicodeDecodeError:
            # maybe log
            return []
```

**Comment by ewjoachim** [comment]
Nice find ! I'll try to do something about it.

**Comment by ewjoachim** [comment]
I've change a lot regarding how files are read, and this seems not to happen anymore. Do you have a precise reproduction raincoat comment to be definitely sure ?

**Comment by ewjoachim** [comment]
Hm, yes it DOES happen actually. Was able to solve, using your suggestion.
